### ISSUE TITLE
problem on the meta device

### ISSUE THREAD

**Issue by WAYKEN-TSE** [RishiHazra/saycanpay#2]
hi, when i run the virtualhome_inference.py,it turned out ''raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")" ,then,as i add the 'to('cuda')',it turned out 'out of memory' since the llm of flan_t5 is too large, how can i fix it,hope for your help.

**Comment by RishiHazra** [comment]
Hi @WAYKEN-TSE. Thanks for using our framework.

Can you tell me the computation resources (GPUs) and the decoding strategy (greedy token, greedy action, beam action) that you're using? It has 11B parameters and takes atleast 4-5 V-100 GPUs with greedy decoding. With beam action decoding strategy, it's even more depending on your beam size.
