### ISSUE TITLE
problem on the 'env'

### ISSUE THREAD

**Issue by WAYKEN-TSE** [RishiHazra/saycanpay#3]
hi,when i want to run the llm_planner.test_plans(),it occurs that the 'env' parameter is a nonetype object,how to fix it?thanks for your answering

**Comment by RishiHazra** [comment]
Hi @WAYKEN-TSE. Is this on the VirtualHome environment? 
Can you try initializing the env variable like so:

```
osname = "linux"
exec_file = '../linux_exec*.x86_64'
exec_file_names = glob.glob(exec_file)
if len(exec_file_names) > 0:
     exec_file_name = exec_file_names[0]
     env = UnityCommunication(file_name=exec_file_name, port="8082", x_display="0")
llm_planner.env = env
rewards, optimal_rewards = llm_planner.test_plans(genplan_file_path)
```

**Comment by WAYKEN-TSE** [comment]
where can i get the exec_file = '../linux_exec*.x86_64'

**Comment by RishiHazra** [comment]
You'd have to follow the setup guide from VirtualHome. Please see this link: https://github.com/xavierpuigf/virtualhome#download-unity-simulator

**Comment by WAYKEN-TSE** [comment]
could you tell me which version of the virtualhome u downloaded in your experiment

**Comment by RishiHazra** [comment]
I think it was v2.3.0.

**Comment by WAYKEN-TSE** [comment]
ok,thanks,also i want to know if you've test the feasible action rate besides the success rate

**Comment by RishiHazra** [comment]
You mean "how many feasible actions in a plan"? No, we didn't. However, we do measure the length of the plan (for optimality) which in some sense also estimates the same.

**Comment by RishiHazra** [comment]
Closing this. Please feel free to open another issue if required.
