### ISSUE TITLE
request for VirtualHome dataset about test-success, test-optimal and test-generalize experiments

### ISSUE THREAD

**Issue by HuiYSir** [RishiHazra/saycanpay#4]
Hello, on VirtualHome dataset, could you provide all test data sets for test-success, test-optimal and test-generalize in $VIRTUALHOME/data/oracle-plans? Thanks.

**Comment by RishiHazra** [comment]
Hi @HuiYSir, here's the link to [test and test-generalize splits](https://drive.google.com/drive/folders/17FUo-D0X74o5uZ8pf4AuJRhQ3qO7X7gK?usp=sharing). For VirtualHome, due to an inadequate number of (post-processed) feasible plans, we used the same test split to measure success and optimality:
